p8105_hw2_jy3186
================
Jiayi Yang
2022-10-02

## Problem 1 being addressed with answers

### Problem 1

Below we import and clean data from
`NYC_Transit_Subway_Entrance_And_Exit_Data.csv`. The process begins with
data import, updates variable names, and selects the columns that will
be used in later parts fo this problem. We update `entry` from `yes` /
`no` to a logical variable. As part of data import, we specify that
`Route` columns 8-11 should be character for consistency with 1-7.

``` r
trans_ent = 
  read_csv(
    "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

As it stands, these data are not “tidy”: route number should be a
variable, as should route. That is, to obtain a tidy dataset we would
need to convert `route` variables from wide to long format. This will be
useful when focusing on specific routes, but may not be necessary when
considering questions that focus on station-level variables.

The following code chunk selects station name and line, and then uses
`distinct()` to obtain all unique combinations. As a result, the number
of rows in this dataset is the number of unique stations.

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

The next code chunk is similar, but filters according to ADA compliance
as an initial step. This produces a dataframe in which the number of
rows is the number of ADA compliant stations.

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

To compute the proportion of station entrances / exits without vending
allow entrance, we first exclude station entrances that do not allow
vending. Then, we focus on the `entry` variable – this logical, so
taking the mean will produce the desired proportion (recall that R will
coerce logical to numeric in cases like this).

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

Lastly, we write a code chunk to identify stations that serve the A
train, and to assess how many of these are ADA compliant. As a first
step, we tidy the data as alluded to previously; that is, we convert
`route` from wide to long format. After this step, we can use tools from
previous parts of the question (filtering to focus on the A train, and
on ADA compliance; selecting and using `distinct` to obtain dataframes
with the required stations in rows).

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

## Problem 2

Mr. Trashwheel data cleaning

``` r
mrtrashwheel_df = read_excel("./Trash_data.xlsx", sheet = "Mr. Trash Wheel", range = ("A2:N550")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster)%>% 
  mutate(sports_balls = round(sports_balls),
         sports_balls = as.integer(sports_balls),
         dumpster = as.integer(dumpster),
         year = as.integer(year),
         wheel_name = "Mr.trash")
```

Prof. Trashwheel data cleaning

``` r
proftrashwheel_df = read_excel("./Trash_data.xlsx", sheet = "Professor Trash Wheel", range = ("A2:M97")) %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
   mutate(sports_balls = 0,
     sports_balls = round(sports_balls),
         sports_balls = as.integer(sports_balls),
         dumpster = as.integer(dumpster),
         wheel_name = "Prof.trash")
proftrashwheel_df
```

    ## # A tibble: 94 × 15
    ##    dumpster month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <int> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, sports_balls <int>, wheel_name <chr>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles,
    ## #   ⁴​polystyrene

Now, combine Prof Trash Wheel with the Mr. Trash Wheel dataset to
produce a single tidy dataset

``` r
combined = bind_rows(mrtrashwheel_df, proftrashwheel_df) %>% 
  janitor::clean_names() %>% 
  drop_na()
combined
```

    ## # A tibble: 568 × 15
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <int> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 558 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, wheel_name <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

To see the data of year 2020

``` r
mrtrashwheel_2020 = 
  mrtrashwheel_df %>% 
  filter(year ==  2020) %>% 
  drop_na()
```

## Description

The row size of the combined dataset is 568.

The column size of the combined dataset is 15.

Key variables are `Dumpster` `Month` `Year` `Date` `Weight (tons)`
`Volume (cubic yards)` `Plastic Bottles` `Polystyrene` `Cigarette Butts`
`Glass Bottles` `Grocery Bags` `Chip Bags` `Sports Balls`
`Homes Powered*`.

The total weight of trash collected by Professor Trash Wheel is 190.12.

The total number of sports balls collected by Mr. Trash Wheel in 2020 is
856.

—End of Problem 2—

## Problem 3

Importing and cleaning the dataset pols-month

``` r
pols_month_df= 
  read_csv("./pols-month.csv") %>% 
  janitor::clean_names() %>% 
      separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(day = lubridate::mdy(day),
         year = as.integer(year),
         month = recode(month, "01" = "Jan", "02" = "Feb", "03" = "Mar",
                        "04" = "Apr", "05" = "May", "06" = "Jun", 
                        "07" = "Jul", "08" = "Aug", "09" = "Sep",
                        "10" = "Oct", "11" = "Nov", "12" = "Dec")
         ) %>% 
   mutate(
    president = ifelse(prez_dem == 0, "gop", "dem")) %>% 
    select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: All formats failed to parse. No formats found.

``` r
pols_month_df
```

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 Jan        23      51     253      23      45     198 dem      
    ##  2  1947 Feb        23      51     253      23      45     198 dem      
    ##  3  1947 Mar        23      51     253      23      45     198 dem      
    ##  4  1947 Apr        23      51     253      23      45     198 dem      
    ##  5  1947 May        23      51     253      23      45     198 dem      
    ##  6  1947 Jun        23      51     253      23      45     198 dem      
    ##  7  1947 Jul        23      51     253      23      45     198 dem      
    ##  8  1947 Aug        23      51     253      23      45     198 dem      
    ##  9  1947 Sep        23      51     253      23      45     198 dem      
    ## 10  1947 Oct        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

Importing and cleaning the dataset snp

``` r
snp_df =
  read_csv("./snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("day", "month", "year"), sep = "/") %>% 
  relocate( year, month, day) %>% 
    mutate(
           year = as.integer(year),
           day = lubridate::mdy(day),
           month = as.integer(month),
            month = recode(month, "01" = "Jan", "02" = "Feb", "03" = "Mar",
                        "04" = "Apr", "05" = "May", "06" = "Jun", 
                        "07" = "Jul", "08" = "Aug", "09" = "Sep",
                        "10" = "Oct", "11" = "Nov", "12" = "Dec"))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: All formats failed to parse. No formats found.

``` r
snp_df
```

    ## # A tibble: 787 × 4
    ##     year month day    close
    ##    <int> <chr> <date> <dbl>
    ##  1    15 Jan   NA     2080.
    ##  2    15 Jan   NA     2063.
    ##  3    15 Jan   NA     2107.
    ##  4    15 Jan   NA     2086.
    ##  5    15 Feb   NA     2068.
    ##  6    15 Feb   NA     2104.
    ##  7    15 Feb   NA     1995.
    ##  8    14 Jan   NA     2059.
    ##  9    14 Mar   NA     2068.
    ## 10    14 Jan   NA     2018.
    ## # … with 777 more rows

Importing and cleaning unemployment data

``` r
unemployment_df =
  read_csv("./unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_rate"
  ) 


unemployment_df
```

    ## # A tibble: 816 × 3
    ##     year month unemployment_rate
    ##    <dbl> <chr>             <dbl>
    ##  1  1948 jan                 3.4
    ##  2  1948 feb                 3.8
    ##  3  1948 mar                 4  
    ##  4  1948 apr                 3.9
    ##  5  1948 may                 3.5
    ##  6  1948 jun                 3.6
    ##  7  1948 jul                 3.6
    ##  8  1948 aug                 3.9
    ##  9  1948 sep                 3.8
    ## 10  1948 oct                 3.7
    ## # … with 806 more rows

Join the datasets of snp and pols and then join unemployment into the
result

``` r
final_merged = 
  left_join(pols_month_df, snp_df) %>% 
   left_join(unemployment_df)
```

    ## Joining, by = c("year", "month")
    ## Joining, by = c("year", "month")

``` r
final_merged
```

    ## # A tibble: 822 × 12
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 Jan        23      51     253      23      45     198 dem      
    ##  2  1947 Feb        23      51     253      23      45     198 dem      
    ##  3  1947 Mar        23      51     253      23      45     198 dem      
    ##  4  1947 Apr        23      51     253      23      45     198 dem      
    ##  5  1947 May        23      51     253      23      45     198 dem      
    ##  6  1947 Jun        23      51     253      23      45     198 dem      
    ##  7  1947 Jul        23      51     253      23      45     198 dem      
    ##  8  1947 Aug        23      51     253      23      45     198 dem      
    ##  9  1947 Sep        23      51     253      23      45     198 dem      
    ## 10  1947 Oct        23      51     253      23      45     198 dem      
    ## # … with 812 more rows, and 3 more variables: day <date>, close <dbl>,
    ## #   unemployment_rate <dbl>

## Description

There are three main datasets in problem 3, pols_month_df (pols) is the
first step data we cleaned, spn_df (spn) is the second step data we
cleaned, and unemployment_df is the third data we cleaned. Then we
merged two of the pol and spn data together and following by merging
unemployment at the end. The final dataset is final_merged. It contains
12 variables and 822 observations. There are two common variables `year`
and `month`. The range of years are from 1947 to 2015. The names of key
variables include: `gov_gop`, `sen_gop`, `rep_gop`, `gov_dem`,
`sen_dem`, `rep_dem` , `president`, `month`, `day`, `close`, and
`unemployment_rate`.
